"use server";

import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';
import { categorySchema, questionSchema } from './validation';

export type ActionResult = { error?: string; success?: string };
async function adminClient() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error('Unauthorized'); const role = user.app_metadata.role ?? user.user_metadata.role; if (role !== 'admin') { const { data } = await supabase.from('users').select('role').eq('id', user.id).maybeSingle(); if (data?.role !== 'admin') throw new Error('Administrator access is required.'); } return supabase; }
function invalidate() { revalidatePath('/'); revalidatePath('/categories'); revalidatePath('/questions'); revalidatePath('/media'); }
export async function saveCategory(_: ActionResult, formData: FormData): Promise<ActionResult> { try { const parsed = categorySchema.safeParse({ name: formData.get('name'), description: formData.get('description'), sortOrder: formData.get('sortOrder') }); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? 'Check the category fields.' }; const supabase = await adminClient(); const id = String(formData.get('id') ?? ''); const payload = { name: parsed.data.name, description: parsed.data.description, sort_order: parsed.data.sortOrder, updated_at: new Date().toISOString() }; const { error } = id ? await supabase.from('categories').update(payload).eq('id', id) : await supabase.from('categories').insert(payload); if (error) return { error: error.code === '23505' ? 'A category with this name already exists.' : error.message }; invalidate(); return { success: id ? 'Category updated.' : 'Category created.' }; } catch (error) { return { error: error instanceof Error ? error.message : 'Could not save category.' }; } }
export async function deleteCategory(id: string): Promise<ActionResult> { try { const supabase = await adminClient(); const { count } = await supabase.from('questions').select('*', { count: 'exact', head: true }).eq('category_id', id).is('deleted_at', null); if (count) return { error: 'Move or delete the category’s questions first.' }; const { error } = await supabase.from('categories').update({ deleted_at: new Date().toISOString() }).eq('id', id); if (error) return { error: error.message }; invalidate(); return { success: 'Category deleted.' }; } catch (error) { return { error: error instanceof Error ? error.message : 'Could not delete category.' }; } }
export async function saveQuestion(_: ActionResult, formData: FormData): Promise<ActionResult> { try { const rawAnswers = JSON.parse(String(formData.get('answers') ?? '[]')) as unknown; const parsed = questionSchema.safeParse({ title: formData.get('title'), categoryId: formData.get('categoryId'), mediaId: formData.get('mediaId') || null, questionType: formData.get('questionType'), difficulty: formData.get('difficulty'), status: formData.get('status'), internalNotes: formData.get('internalNotes'), answers: rawAnswers }); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? 'Check the question fields.' }; const supabase = await adminClient(); const id = String(formData.get('id') ?? ''); const payload = { title: parsed.data.title, category_id: parsed.data.categoryId, media_id: parsed.data.mediaId, question_type: parsed.data.questionType, difficulty: parsed.data.difficulty, status: parsed.data.status, internal_notes: parsed.data.internalNotes, updated_at: new Date().toISOString() }; const result = id ? await supabase.from('questions').update(payload).eq('id', id).select('id').single() : await supabase.from('questions').insert(payload).select('id').single(); if (result.error) return { error: result.error.message }; const questionId = result.data.id; const { error: deleteError } = await supabase.from('answers').delete().eq('question_id', questionId); if (deleteError) return { error: deleteError.message }; const { error: answersError } = await supabase.from('answers').insert(parsed.data.answers.map((answer, display_order) => ({ question_id: questionId, label: answer.label, is_correct: answer.isCorrect, display_order }))); if (answersError) return { error: answersError.message }; invalidate(); return { success: id ? 'Question updated.' : 'Question created.' }; } catch (error) { return { error: error instanceof Error ? error.message : 'Could not save question.' }; } }
export async function deleteQuestion(id: string): Promise<ActionResult> { try { const supabase = await adminClient(); const { error } = await supabase.from('questions').update({ deleted_at: new Date().toISOString() }).eq('id', id); if (error) return { error: error.message }; invalidate(); return { success: 'Question deleted.' }; } catch (error) { return { error: error instanceof Error ? error.message : 'Could not delete question.' }; } }
export async function duplicateQuestion(id: string): Promise<ActionResult> { try { const supabase = await adminClient(); const { data, error } = await supabase.from('questions').select('*, answers(*)').eq('id', id).single(); if (error || !data) return { error: 'Question was not found.' }; const { data: created, error: createError } = await supabase.from('questions').insert({ category_id: data.category_id, media_id: data.media_id, title: `${data.title} (copy)`, question_type: data.question_type, difficulty: data.difficulty, status: 'draft', internal_notes: data.internal_notes }).select('id').single(); if (createError || !created) return { error: createError?.message ?? 'Could not duplicate question.' }; const { error: answerError } = await supabase.from('answers').insert(data.answers.map((answer: { label: string; is_correct: boolean; display_order: number }) => ({ question_id: created.id, label: answer.label, is_correct: answer.is_correct, display_order: answer.display_order }))); if (answerError) return { error: answerError.message }; invalidate(); return { success: 'Question duplicated as a draft.' }; } catch (error) { return { error: error instanceof Error ? error.message : 'Could not duplicate question.' }; } }
export async function uploadMedia(_: ActionResult, formData: FormData): Promise<ActionResult> { try { const file = formData.get('file'); if (!(file instanceof File)) return { error: 'Choose an image or video file.' }; const allowed = ['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime']; if (!allowed.includes(file.type) || file.size > 52_428_800) return { error: 'Use a supported image or video smaller than 50 MB.' }; const supabase = await adminClient(); const path = `${crypto.randomUUID()}/${file.name.replace(/[^a-zA-Z0-9._-]/g, '-')}`; const { error: uploadError } = await supabase.storage.from('question-media').upload(path, file, { contentType: file.type, upsert: false }); if (uploadError) return { error: uploadError.message }; const { error } = await supabase.from('media').insert({ type: file.type.startsWith('image/') ? 'image' : 'video', storage_path: path, file_name: file.name, metadata: { size: file.size, mimeType: file.type } }); if (error) { await supabase.storage.from('question-media').remove([path]); return { error: error.message }; } invalidate(); return { success: 'Media uploaded.' }; } catch (error) { return { error: error instanceof Error ? error.message : 'Could not upload media.' }; } }
export async function deleteMedia(id: string): Promise<ActionResult> { try { const supabase = await adminClient(); const { data, error } = await supabase.from('media').select('storage_path').eq('id', id).single(); if (error || !data) return { error: 'Media was not found.' }; const { count } = await supabase.from('questions').select('*', { count: 'exact', head: true }).eq('media_id', id).is('deleted_at', null); if (count) return { error: 'Remove this media from its questions before deleting it.' }; const { error: storageError } = await supabase.storage.from('question-media').remove([data.storage_path]); if (storageError) return { error: storageError.message }; const { error: deleteError } = await supabase.from('media').delete().eq('id', id); if (deleteError) return { error: deleteError.message }; invalidate(); return { success: 'Media deleted.' }; } catch (error) { return { error: error instanceof Error ? error.message : 'Could not delete media.' }; } }
